### ISSUE TITLE
Is this stun server written on C or on pure javascript?

### ISSUE THREAD

**Issue by Globik** [Thoughtscript/Node_STUN#1]
Just wondering and would like to test it. Why is express? For what? Is there are static html files with client side webrtc code in javascript to test?

**Comment by Globik** [comment]
How to use in practice that node-stun? Could one bind to stun from webrtc ice configs from client side javascript code? Алё, гараж!

**Comment by Thoughtscript** [comment]
Hey! Sorry for the long delay in getting back to you! The express merely exists to do a couple things: serve up Varstate.com .html (also demonstrating how to integrate an ICE/STUN implementation into a regular Express app)!  Pure JavaScript woot! I'll put up a WebRTC demo here in a bit - but you supply a list of ICE servers into the configuration that gets fed into the RTCPeerConnection object! Like this:

`
config = {
			iceServers: [
				{
					urls: [
						'stun.l.google.com:19302',
						'stun1.l.google.com:19302',
						'stun2.l.google.com:19302',
						'stun3.l.google.com:19302',
						'stun4.l.google.com:19302',
						'varstate.com:3478'
					]
				}
			]
		},
`

**Comment by Thoughtscript** [comment]
And to specifically answer your last question there... yes! You bet!  The snippet above shows how to correctly set up a configuration object.  Then, in your clientside you'd use this:

`	var local = new RTCPeerConnection(config);
	var remote = new RTCPeerConnection(config);`

**Comment by Thoughtscript** [comment]
I've been applying to jobs, fending off attempts to steal my intellectual property, and all sorts of other craziness! Take a look here at [http://www.postlib.com](postlib.com) for future explanation of how to put this all together!

**Comment by Globik** [comment]
Ah yes, I see. I shortly tested stun javascript code. It works with internet connectivity. As I on netbook with external modem flash, so I wanted without internet connectivity. One need run chrome.exe with flag -- allow-loopback-in-peer-connection and then all samples work nice. Thank you for your code.
What is the site postlib.com? I can see only one main site with no menu. What for is postlib? Any instructions? What is "begin adventure"?

**Comment by Thoughtscript** [comment]
Ah wow, my apologies for not seeing this previously - it's a personal blog mixing some job information, some JavaScript, Java, and academic work!
